### ISSUE TITLE
Q

### ISSUE THREAD

**Issue by Bravo5542** [marmot-xy/CMBS#1]
Hello, I have reproduced your work and now only reach 73.3% accuracy in the weakly supervised setting, and the test with the model you provided only reaches 73.95%, not 74.2% as stated in the article. Is the downloadable model provided correctly?

**Comment by marmot-xy** [comment]
The weakly supervised model we provided is not the best model. One of the
disadvantages of this task is that the model performance will be a little
unstable, which is also a problem with previous related works. Our previous
weakly supervised model did achieve 74.2%, but unfortunately we forgot to
save that model, so we randomly chose another model(73.95%) later. Maybe
you can try changing the random seed or the value of some parameters, the
performance of the model may reach or even exceed 74.2.

Bravo5542 ***@***.***> 于2022年7月13日周三 12:18写道：
