### ISSUE TITLE
About the resnet feature

### ISSUE THREAD

**Issue by PangRAK** [marmot-xy/CMBS#4]
Hi,
Thank you for the wonderful work.

You extracted features from Resnet in your experiments, where can I find that features?

I would appreciate it if you could answer.

**Comment by PangRAK** [comment]
I found the Baidu Cloud [here](https://pan.baidu.com/s/1aX_ix95xqeaPxjdXmedDxA), 
but is there anything that Google cloud?
Baidu Cloud is too difficult for foreigners to download

**Comment by marmot-xy** [comment]
Sorry, I don't have any more space on my Google cloud.
